### ISSUE TITLE
cant locate the file

### ISSUE THREAD

**Issue by hanzo007** [ilyaevseev/ffmpeg-build#1]
https://github.com/ilyaevseev/ffmpeg-build/blob/aac3704e190edf9c18669d759c0b8271ab1990c9/ffmpeg-nvenc-build.sh#L91

i have both files located in the same folder (ffmpeg-build), but when i run the ffmpeg-nvenc-build.sh with sudo i then get this error: 

./ffmpeg-nvenc-build.sh: 91: ./ffmpeg-nvenc-build.sh: cannot open ./dynlink_cuda.h.patch: No such file

i have tried changing the rights to 777 but still same error

**Comment by ilyaevseev** [comment]
Very strange.
Can you give me access to your buildbox via SSH or TeamViewer?
If you're ready for that, contact me in Telegram https://t.me/Ilya_Evseev

**Comment by ilyaevseev** [comment]
Fixed by fresh commits.
Thank you for TeamViewer session.
