### ISSUE TITLE
ERROR: libass not found using pkg-config while building ffmpeg

### ISSUE THREAD

**Issue by VoodooZ** [ilyaevseev/ffmpeg-build#10]
This is a weird one... I have pkgconfig installed and all that but I assume because we're using some sort of isolated build structure it's not finding it.
Does that mean I'd need to add a function to build libass too so it can get placed with other binaries?

I've seen similar results with libfreetype too before I disabled it..

```
Compiling ffmpeg
Already up-to-date.
ERROR: libass not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

**Comment by ilyaevseev** [comment]
Will answer you tomorrow.
Possibly libass-devel should be installed manually for workaround that.

**Comment by Brainiarc7** [comment]
By any chance, are you on CentOS?

If that's the case, you'll want to install the following:

sudo yum install autoconf automake bzip2 cmake freetype-devel gcc gcc-c++
git libtool make mercurial pkgconfig zlib-devel freetype freetype-devel
libass xz xz-libs xz-devel pxz libvpx-devel yum-utils wget fribidi*
fontconfig* libass-devel bzip2-devel libbz2-devel

See these last two packages?

**Comment by VoodooZ** [comment]
I am on Centos 7 yes.
Libbz2-devel doesn't exist in any of my yum repos.
I installed bzip2-devel so we'll see if that makes any difference.
I had already written a libass build module worst case

Thanks

**Comment by VoodooZ** [comment]
Actually. libbz2-devel is bzip2-devel... and it's installed.
So not that..

**Comment by VoodooZ** [comment]
Here's my first stab at a compileLibAss()

```
compileLibAss() {
    echo "Compiling libass"
    cd "$WORK_DIR/"
    Wget https://github.com/libass/libass/releases/download/0.14.0/libass-0.14.0.tar.xz
    tar Jxvf "libass-0.14.0.tar.xz"
    cd libass-0.14.0
    autoreconf -fiv
    ./configure --prefix="$DEST_DIR" --disable-shared
    make -j$(nproc)
    make install distclean
}
```
Then just need to add a call of compileLibAss early in the call list at the end of the script.

**Comment by VoodooZ** [comment]
And voila! I am now able to complete compilation of ffmpeg! 
Thanks!

**Comment by ilyaevseev** [comment]
Hmm.. libass-devel was in installYumLibs.

Please attach ffbuild/config.log next time.

**Comment by VoodooZ** [comment]
I knew it was installed at system level and double checked it was installed
but pkgconfig was still complaining so Just implemented it seperately..
