### ISSUE TITLE
Can't seem to get nvdec in final binary

### ISSUE THREAD

**Issue by VoodooZ** [ilyaevseev/ffmpeg-build#11]
I'm trying to build a complete ffmpeg for use with jellyfin media server and be able to use my nvidia GPU fully to reduce overhead of transcoding on my server.

After successfully building the default binary provided by this build script, I realised that ffmpeg compilation function was lacking "--enable-nvdec" and added it and started a new build.
It completed successfully but eventhough the resulting binary shows the enable in the list, querying ffmpeg with -hwaccels, -decoders and -encoders, I still can't see any sign of *_nvdec.

Is it built-in ffmpeg or am I just lost?!?

Thanks,

**Comment by Brainiarc7** [comment]
Hello there,

(a). nvdec is automatically detected and enabled IF the nv-codec-headers
package is installed.

(b). nvdec is a bit misleading, as its' an alias to CUDA hwaccel. Can you
see cuda listed under -hwaccels? If so, its' present.

**Comment by VoodooZ** [comment]
Oh i see! I kind of knew there was some ambiguity surrounding that term because nvdec & nvenc used to be cuvid but thanks for confirming...

This is the output of my ffmpeg hwaccels... So I guess I'm all set.  
```
[stephane@filer FFmpeg]$ ~/ffmpeg-build-static-binaries/bin/ffmpeg -hwaccels
ffmpeg version N-93076-ge35c3d8 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --pkg-config-flags=--static --prefix=/home/stephane/ffmpeg-build-static-binaries --bindir=/home/stephane/ffmpeg-build-static-binaries/bin --extra-cflags='-I /home/stephane/ffmpeg-build-static-binaries/include -I /usr/local/cuda/include/' --extra-ldflags='-L /home/stephane/ffmpeg-build-static-binaries/lib -L /usr/local/cuda/lib64/' --extra-libs=-lpthread --enable-cuda --enable-cuda-sdk --enable-cuvid --enable-libnpp --enable-gpl --enable-libass --enable-vaapi --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libfdk-aac --enable-libx264 --enable-libx265 --enable-nonfree --enable-nvenc --enable-nvdec
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 46.100 / 58. 46.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Hardware acceleration methods:
cuda
vaapi
cuvid
```

Still weird that transcoding is taking so long... Most likely more a jellyfin issue though. 

Thanks all...

**Comment by Brainiarc7** [comment]
Perhaps you can show us a sample command from Jellyfin, such as how it
calls up FFmpeg, etc?

**Comment by VoodooZ** [comment]
Actually, weirdly enough my last build seems to run perfectly now..
Mind you I haven't tested subtitles and other features but it's a start.
