### ISSUE TITLE
ERROR: aom >= 1.0.0 not found using pkg-config

### ISSUE THREAD

**Issue by shell1986** [ilyaevseev/ffmpeg-build#13]
Илья привет, пытаюсь установить ffmpeg на чистый Ubuntu 18.04.2 LTS.
В итоге в самом конце мне выдает ошибку 
`ERROR: aom >= 1.0.0 not found using pkg-config`

Перед этим вылезла ошибка 

```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for freetype2 >= 9.10.3... no
configure: error: Package requirements (freetype2 >= 9.10.3) were not met:

No package 'freetype2' found
```
Установил libfreetype6-dev , получил
```
configure: error: Package requirements (fribidi >= 0.19.0) were not met:

No package 'fribidi' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```
а после установки libfribidi-dev следующие

```
checking for CORETEXT... no
checking for DIRECTWRITE... no
checking for harfbuzz >= 0.9.5... no
configure: error: Either DirectWrite (on Windows), CoreText (on OSX), or Fontconfig (Linux, other) is required. If you really want to compile without a system font provider, add --disable-require-system-font-provider
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Compiling ffmpeg
Already up to date.
```

**Comment by shell1986** [comment]
В итоге я вручную установил все библиотеки и программы которые в были в списке. Видно в installAptLibs была ошибка.
Но при этом я столкнулся с новой.
```

./libavutil/cuda_check.h: In function 'ff_cuda_check':
./libavutil/cuda_check.h:38:7: error: 'tcuGetErrorName' undeclared (first use in this function); did you mean 'cuGetErrorName'?
     ((tcuGetErrorName *)cuGetErrorName_fn)(err, &err_name);
       ^~~~~~~~~~~~~~~
       cuGetErrorName
./libavutil/cuda_check.h:38:7: note: each undeclared identifier is reported only once for each function it appears in
./libavutil/cuda_check.h:38:24: error: expected expression before ')' token
     ((tcuGetErrorName *)cuGetErrorName_fn)(err, &err_name);
                        ^
./libavutil/cuda_check.h:39:7: error: 'tcuGetErrorString' undeclared (first use in this function); did you mean 'cuGetErrorString'?
     ((tcuGetErrorString *)cuGetErrorString_fn)(err, &err_string);
       ^~~~~~~~~~~~~~~~~
       cuGetErrorString
./libavutil/cuda_check.h:39:26: error: expected expression before ')' token
     ((tcuGetErrorString *)cuGetErrorString_fn)(err, &err_string);
                          ^
ffbuild/common.mak:60: recipe for target 'libavfilter/vf_scale_cuda.o' failed
make: *** [libavfilter/vf_scale_cuda.o] Error 1
```

**Comment by shell1986** [comment]
В разобрался, история такая.
1 почему не поставились пакеты installAptLibs, я так и не понял. Я установил их вручную.
2 Проблема куда чек видно из-за ошибок репозитория, откатил до версии 4.0
`Clone https://github.com/FFmpeg/FFmpeg -b release/4.0`
Скомпилил, перетащил в /usr/bin
Запустил nvenc энкодер и получил ошибку
`Driver does not support the required nvenc API version. Required: 9.0 Found: 8.1`
В итоге оказалось что **nv-codec-headers.git** обновился, и рекомендуемая версия драйвера 418, при том что официально Nvidia выпустила только 410 для линуксов. В итоге откатился до предыдущей версии. 
`Clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git -b sdk/8.2 `

Еще у меня была проблема с **compileLibfdkcc**, но я ее просто исключил, прошу тоже проверить. Чувствую там тоже нужно предыдущую версию ставить.

**Comment by ilyaevseev** [comment]
Рад, что у Вас всё получилось.
