### ISSUE TITLE
Fribidi Requirments Not Met

### ISSUE THREAD

**Issue by ptowns188** [ilyaevseev/ffmpeg-build#15]
Can anyone help me with this issue on Ubuntu 18.04

configure: error: Package requirements (fribidi >= 0.19.0) were not met:

No package 'fribidi' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FRIBIDI_CFLAGS
and FRIBIDI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Brainiarc7** [comment]
Show us the config.log

**Comment by ptowns188** [comment]
> Show us the config.log
> …

were is the config.log located please?

Thanks

**Comment by ilyaevseev** [comment]
You need to install **libfribidi-dev** package manually before running my script.

By default fribidi is not used at all, see https://github.com/FFmpeg/FFmpeg/blob/master/configure#L238

    --enable-libfribidi      enable libfribidi, improves drawtext filter [no]

My script not enables it.

**Comment by ilyaevseev** [comment]
Closed because cannot be solved without additional info from @ptowns188
