### ISSUE TITLE
centos7 install failed

### ISSUE THREAD

**Issue by rustxj** [ilyaevseev/ffmpeg-build#16]
`vp8/encoder/bitstream.c:320:13: warning: ‘pack_mb_row_tokens’ defined but not used [-Wunused-function]
 static void pack_mb_row_tokens(VP8_COMP *cpi, vp8_writer *w) {
             ^
    [CC] vp8/encoder/boolhuff.c.o
    [CC] vp8/encoder/copy_c.c.o
    [CC] vp8/encoder/dct.c.o
    [CC] vp8/encoder/encodeframe.c.o
    [CC] vp8/encoder/encodeintra.c.o
    [CC] vp8/encoder/encodemb.c.o
    [CC] vp8/encoder/encodemv.c.o
    [CC] vp8/encoder/ethreading.c.o
    [CC] vp8/encoder/denoising.c.o
    [CC] vp8/encoder/lookahead.c.o
    [CC] vp8/encoder/mcomp.c.o
    [CC] vp8/encoder/modecosts.c.o
    [CC] vp8/encoder/onyx_if.c.o
    [CC] vp8/encoder/pickinter.c.o
    [CC] vp8/encoder/picklpf.c.o
    [CC] vp8/encoder/vp8_quantize.c.o
    [CC] vp8/encoder/ratectrl.c.o
    [CC] vp8/encoder/rdopt.c.o
    [CC] vp8/encoder/segmentation.c.o
    [CC] vp8/common/vp8_skin_detection.c.o
    [CC] vp8/encoder/tokenize.c.o
    [CC] vp8/encoder/treewriter.c.o
    [CC] vp8/encoder/mr_dissim.c.o
    [CC] vp8/encoder/x86/vp8_quantize_sse2.c.o
    [CC] vp8/encoder/x86/vp8_quantize_ssse3.c.o
    [CC] vp8/encoder/x86/quantize_sse4.c.o
    [CC] vp8/encoder/x86/denoising_sse2.c.o
    [CC] vp8/encoder/x86/vp8_enc_stubs_sse2.c.o
    [CC] vp8/vp8_dx_iface.c.o
    [CC] vp8/decoder/dboolhuff.c.o
    [CC] vp8/decoder/decodemv.c.o
    [CC] vp8/decoder/decodeframe.c.o
    [CC] vp8/decoder/detokenize.c.o
    [CC] vp8/decoder/onyxd_if.c.o
    [CC] vp8/decoder/threading.c.o
    [CC] vp9/common/vp9_alloccommon.c.o
    [CC] vp9/common/vp9_blockd.c.o
    [CC] vp9/common/vp9_entropy.c.o
    [CC] vp9/common/vp9_entropymode.c.o
    [CC] vp9/common/vp9_entropymv.c.o
    [CC] vp9/common/vp9_frame_buffers.c.o
    [CC] vp9/common/vp9_idct.c.o
    [CC] vp9/common/vp9_filter.c.o
    [CC] vp9/common/vp9_pred_common.c.o
    [CC] vp9/common/vp9_rtcd.c.o
    [CC] vp9/common/vp9_scale.c.o
    [CC] vp9/common/vp9_seg_common.c.o
    [CC] vp9/common/vp9_tile_common.c.o
    [CC] vp9/common/vp9_loopfilter.c.o
    [CC] vp9/common/vp9_thread_common.c.o
    [CC] vp9/common/vp9_mvref_common.c.o
    [CC] vp9/common/vp9_quant_common.c.o
    [CC] vp9/common/vp9_reconinter.c.o
    [CC] vp9/common/vp9_reconintra.c.o
    [CC] vp9/common/vp9_common_data.c.o
    [CC] vp9/common/vp9_scan.c.o
    [CC] vp9/common/vp9_postproc.c.o
    [CC] vp9/common/vp9_mfqe.c.o
    [CC] vp9/common/x86/vp9_idct_intrin_sse2.c.o
    [CC] vp9/common/x86/vp9_highbd_iht4x4_add_sse4.c.o
    [CC] vp9/common/x86/vp9_highbd_iht8x8_add_sse4.c.o
    [CC] vp9/common/x86/vp9_highbd_iht16x16_add_sse4.c.o
    [CC] vp9/vp9_cx_iface.c.o
    [CC] vp9/encoder/vp9_bitstream.c.o
    [CC] vp9/encoder/vp9_context_tree.c.o
    [CC] vp9/encoder/vp9_cost.c.o
    [CC] vp9/encoder/vp9_dct.c.o
    [CC] vp9/encoder/vp9_encodeframe.c.o
    [CC] vp9/encoder/vp9_encodemb.c.o
    [CC] vp9/encoder/vp9_encodemv.c.o
    [CC] vp9/encoder/vp9_ethread.c.o
    [CC] vp9/encoder/vp9_extend.c.o
    [CC] vp9/encoder/vp9_frame_scale.c.o
    [CC] vp9/encoder/vp9_lookahead.c.o
    [CC] vp9/encoder/vp9_multi_thread.c.o
    [CC] vp9/encoder/vp9_mcomp.c.o
    [CC] vp9/encoder/vp9_encoder.c.o
    [CC] vp9/encoder/vp9_picklpf.c.o
    [CC] vp9/encoder/vp9_quantize.c.o
    [CC] vp9/encoder/vp9_ratectrl.c.o
    [CC] vp9/encoder/vp9_rd.c.o
    [CC] vp9/encoder/vp9_rdopt.c.o
    [CC] vp9/encoder/vp9_pickmode.c.o
    [CC] vp9/encoder/vp9_segmentation.c.o
    [CC] vp9/encoder/vp9_speed_features.c.o
    [CC] vp9/encoder/vp9_subexp.c.o
    [CC] vp9/encoder/vp9_svc_layercontext.c.o
    [CC] vp9/encoder/vp9_resize.c.o
    [CC] vp9/encoder/vp9_tokenize.c.o
    [CC] vp9/encoder/vp9_treewriter.c.o
    [CC] vp9/encoder/vp9_aq_cyclicrefresh.c.o
    [CC] vp9/encoder/vp9_skin_detection.c.o
    [CC] vp9/encoder/vp9_noise_estimate.c.o
    [CC] vp9/encoder/x86/vp9_quantize_sse2.c.o
    [CC] vp9/encoder/x86/vp9_quantize_avx2.c.o
    [CC] vp9/encoder/x86/vp9_diamond_search_sad_avx.c.o
    [CC] vp9/encoder/x86/vp9_highbd_block_error_intrin_sse2.c.o
    [CC] vp9/encoder/x86/vp9_dct_intrin_sse2.c.o
    [CC] vp9/encoder/x86/vp9_frame_scale_ssse3.c.o
    [CC] vp9/encoder/x86/vp9_error_avx2.c.o
    [CC] vp9/vp9_dx_iface.c.o
    [CC] vp9/decoder/vp9_decodemv.c.o
    [CC] vp9/decoder/vp9_decodeframe.c.o
    [CC] vp9/decoder/vp9_detokenize.c.o
    [CC] vp9/decoder/vp9_decoder.c.o
    [CC] vp9/decoder/vp9_dsubexp.c.o
    [CC] vp9/decoder/vp9_job_queue.c.o
    [CC] vpx_config.c.o
    [AS] vpx_ports/emms_mmx.asm.o
    [AS] vpx_dsp/x86/intrapred_sse2.asm.o
    [AS] vpx_dsp/x86/intrapred_ssse3.asm.o
    [AS] vpx_dsp/x86/highbd_intrapred_sse2.asm.o
    [AS] vpx_dsp/x86/add_noise_sse2.asm.o
    [AS] vpx_dsp/x86/deblock_sse2.asm.o
    [AS] vpx_dsp/x86/vpx_subpixel_8t_sse2.asm.o
    [AS] vpx_dsp/x86/vpx_subpixel_bilinear_sse2.asm.o
    [AS] vpx_dsp/x86/vpx_subpixel_8t_ssse3.asm.o
    [AS] vpx_dsp/x86/vpx_subpixel_bilinear_ssse3.asm.o
    [AS] vpx_dsp/x86/vpx_high_subpixel_8t_sse2.asm.o
    [AS] vpx_dsp/x86/vpx_high_subpixel_bilinear_sse2.asm.o
    [AS] vpx_dsp/x86/vpx_convolve_copy_sse2.asm.o
    [AS] vpx_dsp/x86/fwd_txfm_ssse3_x86_64.asm.o
vp9/decoder/vp9_decodeframe.c: In function ‘row_decode_worker_hook’:
vp9/decoder/vp9_decodeframe.c:1910:9: warning: variable ‘mi_col’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     int mi_col;
         ^
    [AS] vpx_dsp/x86/inv_wht_sse2.asm.o
    [AS] vpx_dsp/x86/avg_ssse3_x86_64.asm.o
    [AS] vpx_dsp/x86/sad_sse3.asm.o
    [AS] vpx_dsp/x86/sad_ssse3.asm.o
    [AS] vpx_dsp/x86/sad_sse4.asm.o
    [AS] vpx_dsp/x86/sad4d_sse2.asm.o
    [AS] vpx_dsp/x86/sad_sse2.asm.o
    [AS] vpx_dsp/x86/subtract_sse2.asm.o
    [AS] vpx_dsp/x86/highbd_sad4d_sse2.asm.o
    [AS] vpx_dsp/x86/highbd_sad_sse2.asm.o
    [AS] vpx_dsp/x86/ssim_opt_x86_64.asm.o
    [AS] vpx_dsp/x86/subpel_variance_sse2.asm.o
    [AS] vpx_dsp/x86/highbd_variance_impl_sse2.asm.o
    [AS] vpx_dsp/x86/highbd_subpel_variance_impl_sse2.asm.o
    [AS] vp8/common/x86/dequantize_mmx.asm.o
    [AS] vp8/common/x86/idctllm_mmx.asm.o
    [AS] vp8/common/x86/recon_mmx.asm.o
    [AS] vp8/common/x86/subpixel_mmx.asm.o
    [AS] vp8/common/x86/idctllm_sse2.asm.o
    [AS] vp8/common/x86/recon_sse2.asm.o
    [AS] vp8/common/x86/subpixel_sse2.asm.o
    [AS] vp8/common/x86/loopfilter_sse2.asm.o
    [AS] vp8/common/x86/iwalsh_sse2.asm.o
    [AS] vp8/common/x86/subpixel_ssse3.asm.o
    [AS] vp8/common/x86/mfqe_sse2.asm.o
    [AS] vp8/common/x86/loopfilter_block_sse2_x86_64.asm.o
    [AS] vp8/encoder/x86/copy_sse2.asm.o
    [AS] vp8/encoder/x86/copy_sse3.asm.o
    [AS] vp8/encoder/x86/dct_sse2.asm.o
    [AS] vp8/encoder/x86/fwalsh_sse2.asm.o
    [AS] vp8/encoder/x86/block_error_sse2.asm.o
    [AS] vp9/common/x86/vp9_mfqe_sse2.asm.o
    [AS] vp9/encoder/x86/vp9_dct_sse2.asm.o
    [AS] vp9/encoder/x86/vp9_error_sse2.asm.o
    [AS] vp9/encoder/x86/vp9_quantize_ssse3_x86_64.asm.o
    [CREATE] vpx.pc
    [CXX] third_party/googletest/src/src/gtest-all.cc.o
    [CC] test/../ivfenc.c.o
    [CC] test/../md5_utils.c.o
    [CXX] test/../third_party/libwebm/mkvparser/mkvparser.cc.o
    [CXX] test/../third_party/libwebm/mkvparser/mkvreader.cc.o
    [CXX] test/../webmdec.cc.o
    [CC] test/../y4menc.c.o
    [CC] test/../y4minput.c.o
    [CXX] test/active_map_refresh_test.cc.o
    [CXX] test/active_map_test.cc.o
    [CXX] test/add_noise_test.cc.o
    [CXX] test/alt_ref_aq_segment_test.cc.o
    [CXX] test/altref_test.cc.o
    [CXX] test/aq_segment_test.cc.o
    [CXX] test/avg_test.cc.o
    [CXX] test/bench.cc.o
    [CXX] test/borders_test.cc.o
    [CXX] test/byte_alignment_test.cc.o
    [CXX] test/comp_avg_pred_test.cc.o
    [CXX] test/config_test.cc.o
    [CXX] test/convolve_test.cc.o
    [CXX] test/cpu_speed_test.cc.o
    [CXX] test/cq_test.cc.o
    [CXX] test/dct16x16_test.cc.o
    [CXX] test/dct32x32_test.cc.o
    [CXX] test/dct_partial_test.cc.o
    [CXX] test/dct_test.cc.o
    [CXX] test/decode_api_test.cc.o
    [CXX] test/decode_corrupted.cc.o
    [CXX] test/decode_svc_test.cc.o
    [CXX] test/decode_test_driver.cc.o
    [CXX] test/encode_api_test.cc.o
    [CXX] test/encode_test_driver.cc.o
    [CXX] test/error_resilience_test.cc.o
    [CXX] test/external_frame_buffer_test.cc.o
    [CXX] test/fdct8x8_test.cc.o
    [CXX] test/frame_size_tests.cc.o
    [CXX] test/hadamard_test.cc.o
    [CXX] test/idct8x8_test.cc.o
    [CXX] test/idct_test.cc.o
    [CXX] test/invalid_file_test.cc.o
    [CXX] test/keyframe_test.cc.o
    [CXX] test/level_test.cc.o
    [CXX] test/lpf_test.cc.o
    [CXX] test/minmax_test.cc.o
    [CXX] test/partial_idct_test.cc.o
    [CXX] test/pp_filter_test.cc.o
    [CXX] test/predict_test.cc.o
    [CXX] test/quantize_test.cc.o
    [CXX] test/realtime_test.cc.o
    [CXX] test/resize_test.cc.o
    [CXX] test/sad_test.cc.o
    [CXX] test/set_roi.cc.o
In file included from ././vpx_dsp/vpx_dsp_common.h:16:0,
                 from ././vpx_dsp_rtcd.h:16,
                 from test/sad_test.cc:17:
test/sad_test.cc: In member function ‘void {anonymous}::SADx8Test::CheckSADs() const’:
./vpx_ports/mem.h:18:72: error: requested alignment is not an integer constant
 #define DECLARE_ALIGNED(n, typ, val) typ val __attribute__((aligned(n)))
                                                                        ^
test/sad_test.cc:279:5: note: in expansion of macro ‘DECLARE_ALIGNED’
     DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[8]);
     ^
test/sad_test.cc: In member function ‘void {anonymous}::SADx4Test::CheckSADs() const’:
./vpx_ports/mem.h:18:72: error: requested alignment is not an integer constant
 #define DECLARE_ALIGNED(n, typ, val) typ val __attribute__((aligned(n)))
                                                                        ^
test/sad_test.cc:304:5: note: in expansion of macro ‘DECLARE_ALIGNED’
     DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[4]);
     ^
    [CXX] test/sum_squares_test.cc.o
test/sad_test.cc: In member function ‘virtual void {anonymous}::SADx4Test_DISABLED_Speed_Test::TestBody()’:
./vpx_ports/mem.h:18:72: error: requested alignment is not an integer constant
 #define DECLARE_ALIGNED(n, typ, val) typ val __attribute__((aligned(n)))
                                                                        ^
test/sad_test.cc:540:3: note: in expansion of macro ‘DECLARE_ALIGNED’
   DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[4]);
   ^
make[1]: *** [test/sad_test.cc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [.DEFAULT] Error 2
`

Installed 3 this, all failed

**Comment by rustxj** [comment]
test/sad_test.cc:279:5: note: in expansion of macro ‘DECLARE_ALIGNED’
     DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[8]);
     ^
test/sad_test.cc: In member function ‘void {anonymous}::SADx4Test::CheckSADs() const’:
./vpx_ports/mem.h:18:72: error: requested alignment is not an integer constant
 #define DECLARE_ALIGNED(n, typ, val) typ val __attribute__((aligned(n)))
                                                                        ^
test/sad_test.cc:304:5: note: in expansion of macro ‘DECLARE_ALIGNED’
     DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[4]);
     ^
    [CXX] test/sum_squares_test.cc.o
test/sad_test.cc: In member function ‘virtual void {anonymous}::SADx4Test_DISABLED_Speed_Test::TestBody()’:
./vpx_ports/mem.h:18:72: error: requested alignment is not an integer constant
 #define DECLARE_ALIGNED(n, typ, val) typ val __attribute__((aligned(n)))
                                                                        ^
test/sad_test.cc:540:3: note: in expansion of macro ‘DECLARE_ALIGNED’
   DECLARE_ALIGNED(kDataAlignment, uint32_t, exp_sad[4]);
   ^
make[1]: *** [test/sad_test.cc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [.DEFAULT] Error 2

**Comment by ilyaevseev** [comment]
Still actual?

**Comment by ilyaevseev** [comment]
Closed because no answer from reporter.
