### ISSUE TITLE
Thanks for the script - update for Ubuntu18

### ISSUE THREAD

**Issue by journeytosilius** [ilyaevseev/ffmpeg-build#18]
cmake3 doesn't work anymore, and the download link to videolan x264 is dead 

So : I have changed cmake3 to cmake in all ocurrences ( the package was renamed a while ago ) 
and fixed the link to get the latest x264 build at the videloan website. Also changed the filename to unpack x264 correctly.

Just in case you want to update it, and thanks again!

**Comment by ilyaevseev** [comment]
Thank you for feedback!

Can you provide your modifications as patch or (preferred) as pull request?

**Comment by ilyaevseev** [comment]
Implemented by 61e3d01387bb0cfbf381b5cd20e3c1ef75c1235f (x264) and b303c3e9f708e9179a529818886f64e75894ddf1 (cmake).
