### ISSUE TITLE
ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by AdsonCicilioti** [ilyaevseev/ffmpeg-build#2]
Returns

**ERROR: x265 not found using pkg-config**

After clone FFmpeg.

OS: Ubuntu 18.04

**Comment by ilyaevseev** [comment]
Can you give me access to your buildbox via SSH or TeamViewer?
If you're ready for that, please contact me in Telegram https://t.me/Ilya_Evseev

**Comment by AdsonCicilioti** [comment]
Ok... Wait a moment.. I'm making one last attempt.
Maybe I'll get a solution.

**Comment by AdsonCicilioti** [comment]
I solve the x265 error adding this options 
`--extra-libs="-lpthread -lm -lz"`
and
`--extra-ldexeflags="-static" `
on FFmpeg ./configure..
But Now return **ERROR: cuda_sdk not found**.

**Comment by AdsonCicilioti** [comment]
Nice for Team Viewer session!
Fix found!... Update is coming soon!

Thx @ilyaevseev

**Comment by fktkrt** [comment]
Can you update what was the solution to the cuda_sdk problem?

**Comment by ilyaevseev** [comment]
> Can you update what was the solution to the cuda_sdk problem?

See solution in #2

**Comment by fktkrt** [comment]
Yes, but I'm getting the same error when I try to compile a static ffmpeg with the 
`--extra-ldexeflags="-static"` option on Ubuntu 18.04.2. 
`ffmpeg version N-92933-g2659a0fe36`

**Comment by ilyaevseev** [comment]
> Yes, but I'm getting the same error when I try to compile a static ffmpeg with the

The same error - the same solution.
Don't use this option, it's wrong.

**Comment by fktkrt** [comment]
What would be the proper way to compile a static ffmpeg with cuda support?

**Comment by ilyaevseev** [comment]
> What would be the proper way to compile a static ffmpeg with cuda support?

That's impossible because there are no static cuda libs, dynamic only.

**Comment by fktkrt** [comment]
Thank you!
So I have to install `gcc-6 g++-6 nvidia-cuda-toolkit nvidia-kernel-source-410 nvidia-driver-410 nv-codec-headers`, set the cuda locations in environment variables, compile the other options I want with ffmpeg (static what I can), and this is my best possible solution?

**Comment by ilyaevseev** [comment]
My script should do all these steps.
