### ISSUE TITLE
How to install the newly built ffmpeg

### ISSUE THREAD

**Issue by laryan61** [ilyaevseev/ffmpeg-build#20]
I've been able to successfully build ffmpeg with nvenc support from your script. There were a few edits and updates I had to make to complete the build without errors.

The newly compiled binaries are in the \ffmpeg-build-static-binaries\bin directory. How do I install over/replace the current installed ffmpeg?

**Comment by ilyaevseev** [comment]
```
sudo cp -a ./ffmpeg-build-static-binaries/bin/* /usr/local/bin/
```
