### ISSUE TITLE
ERROR: cuda_sdk not found

### ISSUE THREAD

**Issue by flipphos** [ilyaevseev/ffmpeg-build#4]
I tried on Ubuntu 18.04, with Nvidia driver 410.78 and installed CUDA 10.0 based on this article: https://www.pugetsystems.com/labs/hpc/How-to-install-CUDA-9-2-on-Ubuntu-18-04-1184/
===========
= Summary =
===========

Driver:   Not Selected
Toolkit:  Installed in /usr/local/cuda-10.0
Samples:  Installed in /usr/local/cuda-10.0

When I run your script: sudo ./ffmpeg-nvenc-build.sh
I had this "ERROR: cuda_sdk not found"

Below is the last few lines as output:

Compiling ffmpeg
Already up to date.
ERROR: **cuda_sdk not found**

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:91: /libavutil/Makefile: No such file or directory
Makefile:91: /ffbuild/library.mak: No such file or directory
Makefile:93: /fftools/Makefile: No such file or directory
Makefile:94: /doc/Makefile: No such file or directory
Makefile:95: /doc/examples/Makefile: No such file or directory
Makefile:160: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:91: /libavutil/Makefile: No such file or directory
Makefile:91: /ffbuild/library.mak: No such file or directory
Makefile:93: /fftools/Makefile: No such file or directory
Makefile:94: /doc/Makefile: No such file or directory
Makefile:95: /doc/examples/Makefile: No such file or directory
Makefile:160: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Complete!

**Comment by ilyaevseev** [comment]
Hint: check CUDA_DIR value in the [script](../blob/master/ffmpeg-nvenc-build.sh#L18).
Quick fix: `cd /usr/local && ln -s cuda-10.0 cuda`
Then run my script again.

**Comment by flipphos** [comment]
I confirmed that cuda and cuda-10.0 are already linked before I posted. 

I tried Brainiarc7’s git and had the same error. However, after I changed the parameter cuda-sdk to cuda in the last ffmpeg compile step, I could finish the job, and finally get ffmpeg 3.3.x installed. 

My guess was this could probably apply to your script.

**Comment by ilyaevseev** [comment]
> after I changed the parameter cuda-sdk to cuda in the last ffmpeg compile step, I could finish the job, and finally get ffmpeg 3.3.x installed.

Very strange because:

1) Current ffmpeg version is 4.1, not 3.3: https://github.com/FFmpeg/FFmpeg/blob/master/RELEASE

2) The only "cuda-sdk" in my script is in command line of ffmpeg's configure.
The actual https://github.com/FFmpeg/FFmpeg/blob/master/configure describes "--enable-cuda-sdk", not "--enable-cuda".

**Comment by flipphos** [comment]
Sorry, I meant I got the following version after following Brainiarc7’s instructions, the only change I made in order to move the compilation forward was changing “- - enable-cuda-sdk” to “- - enable-cuda” in the command line of ffmpeg’s configure, as inspired by one of the comments down the page.
ffmpeg version N-92952-g5764c9528b Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
configuration: --prefix=/home/hong/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/hong/ffmpeg_build/include --extra-ldflags=-L/home/hong/ffmpeg_build/lib --bindir=/home/hong/bin --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags=-I/usr/local/cuda/include/ --extra-ldflags=-L/usr/local/cuda/lib64/ --nvccflags='-gencode arch=compute_61,code=sm_61 -O2' --enable-gpl --enable-libass --enable-libfdk-aac --enable-libx264 --extra-libs=-lpthread --enable-libx265 --enable-nvenc --enable-nonfree
libavutil      56. 25.100 / 56. 25.100
libavcodec     58. 43.100 / 58. 43.100
libavformat    58. 25.100 / 58. 25.100
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 47.100 /  7. 47.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100

The other version I referred to 3.3 was actually 3.4.4, located under /usr/bin/, which could have probably come from the Plex or other app’s installation. Apologies for the confusion.

I might want to make the same change on yours one day to verify my idea on a clean install of Ubuntu 18.04.

Cheers.

**Comment by ilyaevseev** [comment]
Ok, I added both "--enable-cuda" and "--enable-cuda-sdk".

Can you test it now?

**Comment by flipphos** [comment]
I just did on Ubuntu 18.04.

The script stopped showing the same error. I had to remove the line with "--enable-cuda-sdk” so it carried on to the end.

The resulted ffmpeg version is shown as below:

ffmpeg version N-92963-g1ea5529dd2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
configuration: --pkg-config-flags=--static --prefix=/home/hong/ffmpeg-build-static-binaries --bindir=/home/hong/ffmpeg-build-static-binaries/bin --extra-cflags='-I /home/hong/ffmpeg-build-static-binaries/include -I /usr/local/cuda/include/' --extra-ldflags='-L /home/hong/ffmpeg-build-static-binaries/lib -L /usr/local/cuda/lib64/' --extra-libs=-lpthread --enable-cuda --enable-cuvid --enable-libnpp --enable-gpl --enable-libass --enable-libfdk-aac --enable-vaapi --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-nvenc
libavutil      56. 25.100 / 56. 25.100
libavcodec     58. 43.101 / 58. 43.101
libavformat    58. 25.100 / 58. 25.100
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100

**Comment by ilyaevseev** [comment]
### I tested ffmpeg-build under clean Ubuntu 18.04 installation and it works as expected:
```
lxc-create -t ubuntu -n ffmpeg-builder-bionic -- -r bionic

systemctl start lxc@ffmpeg-builder-bionic

rsync -auxXSH --stats --delete ~/ffmpeg-build /var/lib/lxc/ffmpeg-builder-bionic/rootfs/

lxc-attach -n ffmpeg-builder-bionic
```

### In container:
```
/ffmpeg-build/ffmpeg-nvenc-build.sh

/root/ffmpeg-build-static-binaries/bin/ffmpeg -version | perl -ne 's/ --/\n--/g if /^configuration:/; print'

/root/ffmpeg-build-static-binaries/bin/ffmpeg -encoders 2>/dev/null | grep nvenc

ldd /root/ffmpeg-build-static-binaries/bin/ffmpeg | grep /usr/local
```

### Version and configuration output:
```
ffmpeg version N-92964-g9217dedcd9 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
configuration:
--pkg-config-flags=--static
--prefix=/root/ffmpeg-build-static-binaries
--bindir=/root/ffmpeg-build-static-binaries/bin
--extra-cflags='-I /root/ffmpeg-build-static-binaries/include -I /usr/local/cuda/include/'
--extra-ldflags='-L /root/ffmpeg-build-static-binaries/lib -L /usr/local/cuda/lib64/'
--extra-libs=-lpthread
--enable-cuda
--enable-cuda-sdk
--enable-cuvid
--enable-libnpp
--enable-gpl
--enable-libass
--enable-libfdk-aac
--enable-vaapi
--enable-libfreetype
--enable-libmp3lame
--enable-libopus
--enable-libtheora
--enable-libvorbis
--enable-libvpx
--enable-libx264
--enable-libx265
--enable-nonfree
--enable-nvenc
libavutil      56. 25.100 / 56. 25.100
libavcodec     58. 43.101 / 58. 43.101
libavformat    58. 25.100 / 58. 25.100
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
```

### Encoders output:
```
 V..... h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_hevc           NVIDIA NVENC hevc encoder (codec hevc)
 V..... hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
```

### ldd output:
```
	libnppig.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libnppig.so.10.0 (0x00007f4769d5e000)
	libnppicc.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libnppicc.so.10.0 (0x00007f4769794000)
	libnppidei.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libnppidei.so.10.0 (0x00007f4768e89000)
	libnppc.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libnppc.so.10.0 (0x00007f47655e1000)
```

### So you should check your environment.

I cannot reproduce it as described above.

**Comment by flipphos** [comment]
I can reproduce your result in a new container as well. The script worked.

What I tried in my last email was in a new KVM with Plex and official Nvidia driver installed. Now I am thinking that the Nvidia driver could have made the difference especially when it is CUDA related.

**Comment by stiv-yakovenko** [comment]
Just in case someone has this problem here: if you copy-pasted instruction from nvidia website, please take care of - sign, on the website this sign is not minus sign, just type the command from your keyboard to avoid unreadable chars...

**Comment by schappim** [comment]
Thanks @stiv-yakovenko just had the same issue. The correct comamnd should be: 

`./configure --enable-nonfree --enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64`

**Comment by rezaalimorady** [comment]
@schappim  where should i run this command.
in wich directory?

**Comment by schappim** [comment]
@rezaalimorady 

```git clone https://github.com/ilyaevseev/ffmpeg-build; cd ffmpeg-build; ./configure --enable-nonfree --enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64```

**Comment by rezaalimorady** [comment]
@schappim thanks. iget this error : `-bash: ./configure: No such file or directory`

**Comment by chenle02** [comment]
> @rezaalimorady
> 
> `git clone https://github.com/ilyaevseev/ffmpeg-build; cd ffmpeg-build; ./configure --enable-nonfree --enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64`

I have tried 

`git clone https://github.com/ilyaevseev/ffmpeg-build; cd ffmpeg-build;sudo ./ffmpeg-nvenc-build.sh`

Error message: `ERROR: only CentOS 7, Ubuntu 16.04 or 18.04 are supported now.` 

My system is Ubuntu 20.04.

**Comment by Geremia** [comment]
@flipphos 
> changing “- - enable-cuda-sdk” to “- - enable-cuda”

That worked for me. I wonder why `./configure --help` didn't list `--enable-cuda`; it did list `--enable-cuda-sdk`.
