### ISSUE TITLE
patching of dynlink_cuda.h fails

### ISSUE THREAD

**Issue by VoodooZ** [ilyaevseev/ffmpeg-build#7]
Not sure if it's just a version issue. I'm on CENTOS 7.6.1810 and script pulled cuda-10.0.130-1.x86_64.

```
sed 's#@@PREFIX@@#/usr/local#' ffnvcodec.pc.in > ffnvcodec.pc
sed 's#@@PREFIX@@#/home/stephane/ffmpeg-build-static-binaries#' ffnvcodec.pc.in > ffnvcodec.pc
install -m 0755 -d '/home/stephane/ffmpeg-build-static-binaries/include/ffnvcodec'
install -m 0644 include/ffnvcodec/*.h '/home/stephane/ffmpeg-build-static-binaries/include/ffnvcodec'
install -m 0755 -d '/home/stephane/ffmpeg-build-static-binaries/lib/pkgconfig'
install -m 0644 ffnvcodec.pc '/home/stephane/ffmpeg-build-static-binaries/lib/pkgconfig'
patching file include/ffnvcodec/dynlink_cuda.h
Hunk #1 FAILED at 100.
1 out of 1 hunk FAILED -- saving rejects to file include/ffnvcodec/dynlink_cuda.h.rej
```

**Comment by ilyaevseev** [comment]
Can you attach here two files from `/home/stephane/ffmpeg-build-static-binaries/include/ffnvcodec` directory?

* dynlink_cuda.h
* dynlink_cuda.h.rej

**Comment by VoodooZ** [comment]
odd. the drag and drop feature says it doesn't support that type of file?!? (.h)

**Comment by VoodooZ** [comment]
[dynlink_cuda_error.zip](https://github.com/ilyaevseev/ffmpeg-build/files/2825913/dynlink_cuda_error.zip)

**Comment by ilyaevseev** [comment]
It seems that patching of your dynlink_cuda.h is not needed.
Just ignore "FAILED -- saving rejects" message.

**Comment by VoodooZ** [comment]
yeah. that's what I was doing but just in case you wanted to know.. 

Thanks.
